* UDSE Rebalance

This is a /very/ opinionated rebalance mod for Space Engineers. It makes some
things harder, some things more convenient, and some things easier.

I'll try to keep the list below up to date, but I'd recommend referring to the
git log for details.

This project is available on [[https://github.com/mkaito/SE-UDSE-Rebalance][GitHub]].

The list below includes all numeric details, but here are some notes on /why/ I
even made some of these modifications. These are, of course, only my opinions.

- Power production balance in vanilla leans heavily towards nuclear power. To
  adjust this somewhat, I've doubled renewable energy, tripled H2 power, and
  halved reactor output. Reactors still have the benefit of energy density and
  duration per unit of fuel, but turbines and solar are hopefully not so weak as
  to be completely obsolete the moment you find some Uranium.
- Wheels, especially large grid, are woefully underpowered. Have you ever tried
  to build a moderately sized large grid rover, only to have to put as many (or
  more) thrusters on it as if you were building a ship?
- Since I pretty much always play with a deep ores mod, increase ore detector range.
- Ship grinder radius increased so that grinder pits don't end up with blocks stuck between grinders.
- Ship drill radius increased so that large grid drills are actually worth using.
- Ship welder radius increased so that you can use fewer, since they are a huge
  performance hog.
- Spotlights and lights in general need way more range.
- Armour, thrusters and cockpits have had their damage multiplier reduced quite
  a bit. Heavy armour is now actually worth using, even on small grid.
- The whole economy system is a joke, but I use safe zones anyway, so I've added
  a recipe to craft the chips. Also reduced power usage of safe zones and made
  chips last 24h.
- H2 thrusters use less fuel so H2 ships are not 60% H2 tanks by volume.
- Thruster force magnitude increased a fair bit, to make compact and aesthetic builds viable.
  
- All adjustments apply to modded blocks that share the same Type ID as vanilla blocks.
- Some subtypes have been explicitly excluded:
  - Life'Tech Powers fusion reactors
  - MES NPC thrusters
  - Rider's Helicarrier Thrusters MK II
  - Nanite Control Factory (is actually a welder, increasing radius turns it into a death machine)
  
** Thruster rebalance concept

Currently testing a locale-based thruster rebalance model. 

Ion and Atmospheric thrusters can only be used in one locale (space and atmosphere respectively), while H2 thrusters can be used anywhere. The idea is that locale-restricted thrusters are more optimized for their specific locale, and are thus much more powerful. They also use much more power to retain a semblance of balance.

H2 thrusters can be used anywhere and require no power, but require plumbing and explosive H2 tanks. They are also weaker, but consume much less fuel.

Single-locale ships can use much fewer thrusters, but require extra power generation. The increased power output from solar panels and batteries will help.

Locale-agnostic ships are fuel efficient, but require comparatively more thrusters, more even than using both locale-specific thruster types together.

Thrust values significantly favour large grid large thrusters

I'm not sure how this will work out, but it's worth a try.

** Character

A mild jetpack nerf is included. Its power has been fine tuned so you can get
yourself out of a hole in 1.2G, if you angle yourself correctly and use both
upward and forward acceleration, but you wont hover in place in 1G or higher.

Oxygen consumption has been increased 8-fold in order to reduce suit autonomy on
foot.

Either of these can be disabled in the config file, found in your world storage
folder after loading the game at least once with this mod.

** Blocks

- Also courtesy of Enenra, a script that severely reduces damage taken for all armor blocks, especially heavy armour, and doubly so for small grid armour.
  - Large grid light armor takes 50% less damage.
  - Small grid light armor takes 60% less damage.
  - Large grid heavy armor takes 60% less damage.
  - Small grid heavy armor takes 80% less damage.
- Cockpits and thrusters take half as much damage.
- Wind Turbines produce 4x the output.
- Solar panels produce 4x the output.
- Nuclear reactors produce half the output.
- Hydrogen engines produce 3x the output, 3x fuel efficiency.
- Battery maximum output x2
- Energy density of H2 tripled, effectively 9x more efficient in H2 engines.
- Oxygen farms produce 10x the output.
- Large grid wheels have 20x the power, friction, use 2.5x the power, and take 5x less damage.
- Small grid wheels have 8x the power, friction and take 5x less damage.
- Ore detectors have 20x the range (Using range over 1.2k on planets is problematic. Blame Keen.)
- Laser antenna uses 90% less damage while lasing.
- Laser antenna does not require line of sight (configurable).
- Ship grinder radius increased 6x for large grid, 1.25x for small grid.
- Ship drill radius increased 6x for large grid, 1.4x for small grid.
- Ship welder radius increased 6x for large grid, 2x for small grid.
- Spotlight range increased to 780m on large grid, 480m on small.
- Interior lights (and corner lights, panels, etc) range increased to 200m on large grid, 100m on small.
- Safe Zone
  - Minimum power usage set to 1MW
  - Maximum power usage set to 100MW
  - Zone Chips last 24h
  - Zone Chips craftable in assembler (not basic, the big one)
- Thruster rebalance
  - All thrusters have 2x thrust for LG and 1.2x for SG
  - H2 fuel usage x0.4
